server:
  port: 7900
spring:
  jpa:
    generate-ddl: false  # 启动时要不要生成 ddl 语句，因为我们自己写了，就不需要生成了 false
    show-sql: false      # 打印sql语句
    hibernate:           # jpa 依赖 hebernate, 所以对 hebernate 进行配置
      ddl-auto: none     # 启动时不做 ddl 语句的处理
  datasource:
    platform: h2         # 使用h2数据库
    schema: classpath:schema.sql  # 建表语句
    data: classpath:data.sql      # 数据
logging:
  level:
    root: INFO
    org.hibernate: INFO  # 这三句，显示sql语句，同时把参数都打印出来
    org.hibernate.type.descripter.sql.BasicBinder: TRACE
    org.hibernate.type.descripter.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG