DROP TABLE user if EXISTS;

CREATE TABLE user (
    id bigint generated by default as IDENTITY, -- H2 语法，表示自增主键
    username varchar(40),
    name varchar(20),
    age int(3),
    balance DECIMAL(10, 2),
    PRIMARY key(id)
);